name: Build WDA IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2  # Menggunakan patch versi terbaru yang kompatibel

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build WebDriverAgent
        run: |
          xcodebuild build-for-testing \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -sdk iphoneos \
            -derivedDataPath build

      - name: Package to IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app Payload/
          zip -r WebDriverAgent.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4.6.0  # Menggunakan patch versi terbaru
        with:
          name: WebDriverAgent-IPA
          path: WebDriverAgent.ipa
